FROM wildflower/base-cpu

MAINTAINER lue.her@gmail.com

RUN apt-get update && apt-get install -y --no-install-recommends \
        build-essential \
        libgl1-mesa-glx \
        && \
    rm -rf /var/lib/apt/lists/*

RUN git clone https://github.com/WildflowerSchools/suppose.git && \
    cd suppose && \
    python setup.py install

ENTRYPOINT ["/opt/conda/bin/suppose"]
