# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import suppose_pb2 as suppose__pb2


class PoseExtractorStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetPose = channel.unary_unary(
        '/suppose.PoseExtractor/GetPose',
        request_serializer=suppose__pb2.Image.SerializeToString,
        response_deserializer=suppose__pb2.Frame.FromString,
        )
    self.StreamPoses = channel.stream_stream(
        '/suppose.PoseExtractor/StreamPoses',
        request_serializer=suppose__pb2.Image.SerializeToString,
        response_deserializer=suppose__pb2.Frame.FromString,
        )
    self.StreamPosesFromVideo = channel.unary_stream(
        '/suppose.PoseExtractor/StreamPosesFromVideo',
        request_serializer=suppose__pb2.File.SerializeToString,
        response_deserializer=suppose__pb2.Frame.FromString,
        )


class PoseExtractorServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetPose(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def StreamPoses(self, request_iterator, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def StreamPosesFromVideo(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_PoseExtractorServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetPose': grpc.unary_unary_rpc_method_handler(
          servicer.GetPose,
          request_deserializer=suppose__pb2.Image.FromString,
          response_serializer=suppose__pb2.Frame.SerializeToString,
      ),
      'StreamPoses': grpc.stream_stream_rpc_method_handler(
          servicer.StreamPoses,
          request_deserializer=suppose__pb2.Image.FromString,
          response_serializer=suppose__pb2.Frame.SerializeToString,
      ),
      'StreamPosesFromVideo': grpc.unary_stream_rpc_method_handler(
          servicer.StreamPosesFromVideo,
          request_deserializer=suppose__pb2.File.FromString,
          response_serializer=suppose__pb2.Frame.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'suppose.PoseExtractor', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
